### ISSUE TITLE
Roadmap to version 1.0

### ISSUE THREAD

**Issue by Mondei1** [ch-a-os/DocSort#1]
This issue covers most of our ideas we want to implement before we are releasing the first user-friendly version of DocSort. This list can be updated at every time. 

The lists are ordered from important (top) to less important (bottom).

### Basic features:
- [ ] Way to upload one or multiple documents to the backend
- [ ] Way to view all documents
- [ ] Way to create document groups (e.g. site 1.0, 1.1, 1.2, *you get the idea)
- [x] Taggable documents
- [ ] Way to view all tags and there related documents
- [x] Multi user support
- [ ] User settings (e.g. theme to use, language, use encryption?, accessible from network or internet? or some other default options)
- [ ] Intelligent search (including tags, scanned text, title and description)
- [ ] Document scan with OCR algorithm to digitalise scanned text (not required for PDFs or text files) 
- [ ] Modern and simple UI

### Supported file types:
- [ ] PNGs
- [ ] JPGs
- [ ] PDFs
- [ ] Plain text

Planned date for first release is the **29th March 2019**, but this is very experimental and could be reached If we developing everything at the same motivation as now.

**Comment by 720degreeLotus** [comment]
I splitted up all the named features and mechanics (and even smore more) into 3 milestones.
Can you please review these and, if you accept those, close this issue here?
If you feel that one or more things have been lost/forgotten, just add them to one of the milestones.
